version: '3.7'

services:
  enclave:
    image: sgx-sdk
    build:
      context: enclave
      dockerfile: Dockerfile
    ports:
      - 5552:5552
    volumes:
      - ./enclave/safetrace/bin/safetrace-app:/usr/src/enclave/safetrace/bin/safetrace-app
      - type: bind
        source: /var/run/aesmd/aesm.socket
        target: /var/run/aesmd/aesm.socket
    devices:
      - /dev/isgx
    working_dir: /usr/src/enclave/safetrace/bin
    environment:
      - IAS_SGX_SPID
      - IAS_SGX_PRIMARY_KEY
    command: ./safetrace-app

  api-server:
    #image: safetrace-api-server
    build:
      context: api-server
      dockerfile: Dockerfile
    volumes:
      - ./api-server/index.js:/usr/src/app/index.js
    #working_dir: /usr/src/app
    ports:
      - "8080:8080"
    command: "node index.js"

